CC=gcc

all: exercise1 exercise2 exercise3 exercise4

exercise1: exercise1.o
	$(CC) exercise1.o -o exercise1

exercise1.o: exercise1.c
	$(CC) -c exercise1.c

exercise2: exercise2.o
	$(CC) exercise2.o -o exercise2

exercise2.o: exercise2.c
	$(CC) -c exercise2.c	

exercise3: exercise3.o
	$(CC) exercise3.o -o exercise3

exercise3.o: exercise3.c
	$(CC) -c exercise3.c	

exercise4: exercise4.o
	$(CC) exercise4.o -o exercise4

exercise4.o: exercise4.c
	$(CC) -c exercise4.c	

clean:
	rm -f exercise1 exercise2 exercise3 exercise4 *.o
